"""Add to Messages 'answer' & rename 'message' to 'question'

Revision ID: b6e0afd8fe19
Revises: f789f5bad5b4
Create Date: 2023-10-17 15:00:36.633139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e0afd8fe19'
down_revision: Union[str, None] = 'f789f5bad5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('answer', sa.Text(), nullable=True))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'answer')
    op.drop_column('messages', 'question')
    # ### end Alembic commands ###
