"""Add 'banned'-column to User model

Revision ID: bdbd53c6c392
Revises: 02527c26eaed
Create Date: 2023-10-24 15:35:52.036978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbd53c6c392'
down_revision: Union[str, None] = '02527c26eaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
