"""Set autoincrement=False to Messages id column

Revision ID: f789f5bad5b4
Revises: 0231046bfa10
Create Date: 2023-10-17 12:55:28.041785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f789f5bad5b4'
down_revision: Union[str, None] = '0231046bfa10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
